name: Java CI with Maven - Test and package

on:
  pull_request:
    branches: [ "main" ] # déclenchement uniquement sur PR vers main

jobs:
  build:
    runs-on: ubuntu-latest # OS utilisé pour exécuter le job

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'corretto'

      - name: Build with Maven
        run: mvn -B package

